import React from 'react';
import { Page, Text, Document, StyleSheet } from '@react-pdf/renderer';
import { AiMessage } from '../providers/AiMessagesProvider';

const styles = StyleSheet.create({
  body: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingHorizontal: 40,
  },
  header: {
    fontSize: 10,
    marginBottom: 20,
    textAlign: 'center',
    color: 'grey',
  },
  title: {
    fontSize: 12,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 10,
    margin: 12,
    textAlign: 'center',
  },
  image: {
    marginVertical: 5,
    marginHorizontal: 150,
  },
  text: {
    margin: 8,
    fontSize: 10,
    textAlign: 'left',
  },
});

type Props = {
  messages: AiMessage[];
};

const MyDocument = ({ messages }: Props) => (
  <Document>
    <Page style={styles.body}>
      <Text style={styles.header} fixed>
        ~ Generated by Auto Cortext ~
      </Text>
      {messages.map((message) => (
        <Text style={styles.text}>{message.content}</Text>
      ))}
    </Page>
  </Document>
);

export default MyDocument;
