import React from 'react';
import { Page, Text, Document, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  body: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingHorizontal: 40,
  },
  header: {
    fontSize: 10,
    marginBottom: 20,
    textAlign: 'center',
    color: 'grey',
  },
  title: {
    fontSize: 12,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 10,
    margin: 12,
    textAlign: 'center',
  },
  image: {
    marginVertical: 5,
    marginHorizontal: 150,
  },
  text: {
    margin: 12,
    fontSize: 10,
    textAlign: 'justify',
  },
});

type Props = {
  report: string;
};

const MyDocument = ({ report }: Props) => (
  <Document>
    <Page style={styles.body}>
      <Text style={styles.header} fixed>
        ~ Generated by CORETEXT ~
      </Text>
      <Text style={styles.text}>{report}</Text>
    </Page>
  </Document>
);

export default MyDocument;
