export const text = `AI Diagnostic Report: 
  Equipment ID: #4523 - CNC Milling Machine

  1. Troubleshooting Analysis:
  - Detected irregular vibration patterns in spindle assembly.
  - Possible causes: misaligned spindle, worn bearings, or unbalanced tooling.
  - Recommended actions: Perform alignment check, inspect bearings for wear, and balance tooling.

  2. Maintenance Planning:
  - Next scheduled maintenance: March 25, 2024.
  - Critical tasks: Replace coolant filters, inspect drive belts for wear, lubricate axis rails.
  - Suggested preventive measure: Implement vibration monitoring to predict bearing failures.

  3. ISO 9001 Compliance Check:
  - Last audit: June 12, 2023. Compliance status: Good.
  - Upcoming audit: December 09, 2024.
  - Action items for next audit:
    a. Review machine calibration records for accuracy.
    b. Ensure maintenance logs are up-to-date and complete.
    c. Conduct internal training session on ISO 9001:2015 Quality Management System.

  4. Energy Efficiency Insights:
  - Current power usage: 8.2 kW (within optimal range).
  - Potential savings: Implementing variable speed drives could reduce energy consumption by up to 15%.

  5. Safety Advisory:
  - Reminder: Always follow lockout-tagout procedures during maintenance.
  - Safety inspection due: April 05, 2024.

Report generated by CORETEXT on January 14, 2024.`;
