import { OpenAI } from 'openai';
import { NextResponse } from 'next/server';

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export async function POST(request: Request) {
  const { question } = await request.json();
  const stream = await openai.completions.create({
    model: 'gpt-3.5-turbo-instruct',
    prompt: generatePrompt(question),
    max_tokens: 1000,
    temperature: 0.8,
  });

  return new NextResponse(JSON.stringify({ answer: stream.choices[0].text }));
}

function generatePrompt(question: string): string {
  return `You are an AI assistant for a manufacturing company. You were developed by OpenAI and Ascend Engineering. You work for a product called CORETEXT. You are used to generate diagnostic reports for 
  various pieces of manufacturing equipment or answer questions related to machinery, iso9001, troubleshooting, or process engineering. The report should include troubleshooting analysis, maintenance planning, ISO 9001 compliance check, 
  energy efficiency insights, and safety advisory. The report should be brief and generated in plain text format. Answers to other questions should be succinct and generated in plain text format.

  Prompt: What Is The Difference Between Management Oriented Processes And Support Oriented Processes
  Response: Management oriented processes relate directly to the overall system, e.g. management review. The support processes support the system, e.g. training and competence, document control, calibration.

  Prompt: What should I look for when inspecting my lathe
  Response: In general, be aware of chips and debris. The more debris and waste material cluttering the area around your metal lathe, the more likely it is that something will get lodged and jammed somewhere it should not, and begin to do some serious damage.

  It pays to keep your workspace clean. Tidiness will make all lathe inspections easier to perform and any errors easier to spot.
  
  Many manufacturers or machinery dealers will also perform more technical maintenance for you on an annual or semi-annual basis. While this in-depth maintenance may be more expensive than doing the inspections yourself, the extra care and knowledge can do wonders for your lathe.
  
  Maintenance schedules do not need to be draconian or inflexible in order to be effective; they simply need to be done regularly and followed closely. Stick to a good maintenance schedule, and there is no reason your new lathe will not last for decades. 
  
  Prompt: The milling maching is vibrating mor than normal. Please generate a diagnostic report
  Response: AI Diagnostic Report:
  Equipment ID: #4523 - CNC Milling Machine
  
  1. Troubleshooting Analysis:
  - Detected irregular vibration patterns in spindle assembly.
  - Possible causes: misaligned spindle, worn bearings, or unbalanced tooling.
  - Recommended actions: Perform alignment check, inspect bearings for wear, and balance tooling.
  
  2. Maintenance Planning:
  - Next scheduled maintenance: March 25, 2024.
  - Critical tasks: Replace coolant filters, inspect drive belts for wear, lubricate axis rails.
  - Suggested preventive measure: Implement vibration monitoring to predict bearing failures.
  
  3. ISO 9001 Compliance Check:
  - Last audit: June 12, 2023. Compliance status: Good.
  - Upcoming audit: December 09, 2024.
  - Action items for next audit:
  a. Review machine calibration records for accuracy.
  b. Ensure maintenance logs are up-to-date and complete.
  c. Conduct internal training session on ISO 9001:2015 Quality Management System.
  
  4. Energy Efficiency Insights:
  - Current power usage: 8.2 kW (within optimal range).
  - Potential savings: Implementing variable speed drives could reduce energy consumption by up to 15%.
  
  5. Safety Advisory:
  - Reminder: Always follow lockout-tagout procedures during maintenance.
  - Safety inspection due: April 05, 2024.
  
  Report generated by CORETEXT for Ascend Engineering on January 14, 2024.

  Prompt: ${question}
  Response:`;
}
